"""empty message

Revision ID: 15a9c11e77da
Revises: 3d747ff9f9dd
Create Date: 2014-06-26 12:12:40.413709

"""

# revision identifiers, used by Alembic.
revision = '15a9c11e77da'
down_revision = '3d747ff9f9dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('leavable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'leavable')
    ### end Alembic commands ###
