"""empty message

Revision ID: 178ec8c0b4ef
Revises: 52f90510e7b2
Create Date: 2014-07-17 10:35:02.617313

"""

# revision identifiers, used by Alembic.
revision = '178ec8c0b4ef'
down_revision = '52f90510e7b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('POS', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('POS', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('moon_goo', sa.Column('last_editor', sa.Integer(), nullable=True))
    op.add_column('moon_goo', sa.Column('last_updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moon_goo', 'last_updated')
    op.drop_column('moon_goo', 'last_editor')
    op.drop_column('POS', 'date_added')
    op.drop_column('POS', 'author')
    ### end Alembic commands ###
