"""empty message

Revision ID: 1a6489aaab41
Revises: 40af05c5d658
Create Date: 2014-07-01 01:38:57.527051

"""

# revision identifiers, used by Alembic.
revision = '1a6489aaab41'
down_revision = '40af05c5d658'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mumble_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_segment', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mumble_operation')
    ### end Alembic commands ###
