"""empty message

Revision ID: 1a8236ac2188
Revises: 4b07f409c0c7
Create Date: 2014-06-25 18:52:54.590931

"""

# revision identifiers, used by Alembic.
revision = '1a8236ac2188'
down_revision = '4b07f409c0c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['api_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_characters')
    ### end Alembic commands ###
