"""empty message

Revision ID: 1e5cd35569af
Revises: 51d27a60b822
Create Date: 2014-06-24 22:26:10.421081

"""

# revision identifiers, used by Alembic.
revision = '1e5cd35569af'
down_revision = '51d27a60b822'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_keys',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['key_id'], ['api_key.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_keys')
    ### end Alembic commands ###
