"""empty message

Revision ID: 2004d963dc61
Revises: c24c1873213
Create Date: 2014-06-29 22:23:49.887653

"""

# revision identifiers, used by Alembic.
revision = '2004d963dc61'
down_revision = 'c24c1873213'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alliance', sa.Column('ticker', sa.String(length=64), nullable=True))
    op.add_column('corporation', sa.Column('ticker', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporation', 'ticker')
    op.drop_column('alliance', 'ticker')
    ### end Alembic commands ###
