"""empty message

Revision ID: 28d7269159f8
Revises: 1a6489aaab41
Create Date: 2014-07-01 02:10:44.658754

"""

# revision identifiers, used by Alembic.
revision = '28d7269159f8'
down_revision = '1a6489aaab41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mumble_operation', sa.Column('started', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mumble_operation', 'started')
    ### end Alembic commands ###
