"""empty message

Revision ID: 2ab6efed78c3
Revises: 1a8236ac2188
Create Date: 2014-06-25 19:09:19.238436

"""

# revision identifiers, used by Alembic.
revision = '2ab6efed78c3'
down_revision = '1a8236ac2188'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
