"""empty message

Revision ID: 35ed9cf2c4de
Revises: 28d7269159f8
Create Date: 2014-07-01 16:10:06.449442

"""

# revision identifiers, used by Alembic.
revision = '35ed9cf2c4de'
down_revision = '28d7269159f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_corp_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corp_id'], ['corporation.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_corp_rule')
    ### end Alembic commands ###
