"""empty message

Revision ID: 375e41e4e7f1
Revises: 2ab6efed78c3
Create Date: 2014-06-25 19:11:35.588705

"""

# revision identifiers, used by Alembic.
revision = '375e41e4e7f1'
down_revision = '2ab6efed78c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
