"""empty message

Revision ID: 3a2fceb7d1e
Revises: 38d38556add
Create Date: 2014-06-24 18:39:37.554598

"""

# revision identifiers, used by Alembic.
revision = '3a2fceb7d1e'
down_revision = '38d38556add'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('desc', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'desc')
    ### end Alembic commands ###
