"""empty message

Revision ID: 3c2a138f2ccd
Revises: 3a2fceb7d1e
Create Date: 2014-06-24 20:18:31.528925

"""

# revision identifiers, used by Alembic.
revision = '3c2a138f2ccd'
down_revision = '3a2fceb7d1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allianceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allianceId'], ['alliance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('corpId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corpId'], ['corporation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    op.drop_table('corporation')
    op.drop_table('alliance')
    ### end Alembic commands ###
