"""empty message

Revision ID: 3d747ff9f9dd
Revises: 4346dca42023
Create Date: 2014-06-26 11:34:28.010405

"""

# revision identifiers, used by Alembic.
revision = '3d747ff9f9dd'
down_revision = '4346dca42023'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_member', sa.Column('app_status', sa.SmallInteger(), nullable=True))
    op.add_column('group_member', sa.Column('app_text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_member', 'app_text')
    op.drop_column('group_member', 'app_status')
    ### end Alembic commands ###
