"""empty message

Revision ID: 40af05c5d658
Revises: 572c476c78c1
Create Date: 2014-06-29 23:34:57.710642

"""

# revision identifiers, used by Alembic.
revision = '40af05c5d658'
down_revision = '572c476c78c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mumble_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('account_type', sa.SmallInteger(), nullable=True),
    sa.Column('op_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mumble_account')
    ### end Alembic commands ###
