"""empty message

Revision ID: 4924d2694121
Revises: 3e9f254f670b
Create Date: 2014-06-28 23:12:35.795214

"""

# revision identifiers, used by Alembic.
revision = '4924d2694121'
down_revision = '3e9f254f670b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ping_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servers', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ping_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ping_target')
    op.drop_table('ping_server')
    ### end Alembic commands ###
