"""empty message

Revision ID: 4b07f409c0c7
Revises: 4d734433a63d
Create Date: 2014-06-25 15:42:35.111409

"""

# revision identifiers, used by Alembic.
revision = '4b07f409c0c7'
down_revision = '4d734433a63d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_keys')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_keys',
    sa.Column('character_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], [u'character.id'], name=u'character_keys_ibfk_1'),
    sa.ForeignKeyConstraint(['key_id'], [u'api_key.id'], name=u'character_keys_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
