"""empty message

Revision ID: 4dc81054da1
Revises: 596a8b1642b7
Create Date: 2014-07-16 23:38:29.706793

"""

# revision identifiers, used by Alembic.
revision = '4dc81054da1'
down_revision = '596a8b1642b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POS',
    sa.Column('moonid', sa.Integer(), nullable=False),
    sa.Column('tower_typeid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('moonid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('POS')
    ### end Alembic commands ###
