"""empty message

Revision ID: 51d27a60b822
Revises: 3c2a138f2ccd
Create Date: 2014-06-24 21:48:40.892748

"""

# revision identifiers, used by Alembic.
revision = '51d27a60b822'
down_revision = '3c2a138f2ccd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('owner', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'owner')
    ### end Alembic commands ###
