"""empty message

Revision ID: 52f90510e7b2
Revises: 4dc81054da1
Create Date: 2014-07-16 23:40:55.638857

"""

# revision identifiers, used by Alembic.
revision = '52f90510e7b2'
down_revision = '4dc81054da1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon_goo',
    sa.Column('moonid', sa.Integer(), nullable=False),
    sa.Column('goo_1_typeid', sa.Integer(), nullable=True),
    sa.Column('goo_2_typeid', sa.Integer(), nullable=True),
    sa.Column('goo_3_typeid', sa.Integer(), nullable=True),
    sa.Column('goo_4_typeid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('moonid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon_goo')
    ### end Alembic commands ###
