"""empty message

Revision ID: 572c476c78c1
Revises: 2004d963dc61
Create Date: 2014-06-29 22:26:29.562858

"""

# revision identifiers, used by Alembic.
revision = '572c476c78c1'
down_revision = '2004d963dc61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
