"""empty message

Revision ID: 596a8b1642b7
Revises: f0b1830d528
Create Date: 2014-07-14 09:24:08.561529

"""

# revision identifiers, used by Alembic.
revision = '596a8b1642b7'
down_revision = 'f0b1830d528'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('author', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'author')
    ### end Alembic commands ###
