"""empty message

Revision ID: 5d0689d364f
Revises: 15a9c11e77da
Create Date: 2014-06-26 13:58:18.112977

"""

# revision identifiers, used by Alembic.
revision = '5d0689d364f'
down_revision = '15a9c11e77da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_parent')
    ### end Alembic commands ###
