"""empty message

Revision ID: 7844211fb55
Revises: c5242907c1e
Create Date: 2014-07-30 10:23:03.502189

"""

# revision identifiers, used by Alembic.
revision = '7844211fb55'
down_revision = 'c5242907c1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('lastKnownShip', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'lastKnownShip')
    ### end Alembic commands ###
