"""empty message

Revision ID: 94ff4532762
Revises: aeddca1cd6a
Create Date: 2014-07-20 10:36:18.938820

"""

# revision identifiers, used by Alembic.
revision = '94ff4532762'
down_revision = 'aeddca1cd6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=True),
    sa.Column('action_item', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_general')
    ### end Alembic commands ###
