"""empty message

Revision ID: bf599e87f79
Revises: df542bbde1b
Create Date: 2014-07-11 13:06:55.385913

"""

# revision identifiers, used by Alembic.
revision = 'bf599e87f79'
down_revision = 'df542bbde1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
