"""empty message

Revision ID: c24c1873213
Revises: 4924d2694121
Create Date: 2014-06-29 00:34:33.113105

"""

# revision identifiers, used by Alembic.
revision = 'c24c1873213'
down_revision = '4924d2694121'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
