"""empty message

Revision ID: c5242907c1e
Revises: 4113ead527a4
Create Date: 2014-07-29 16:36:55.598146

"""

# revision identifiers, used by Alembic.
revision = 'c5242907c1e'
down_revision = '4113ead527a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporation', sa.Column('memberCount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporation', 'memberCount')
    ### end Alembic commands ###
