"""empty message

Revision ID: df542bbde1b
Revises: 35ed9cf2c4de
Create Date: 2014-07-11 12:38:44.507718

"""

# revision identifiers, used by Alembic.
revision = 'df542bbde1b'
down_revision = '35ed9cf2c4de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_permission')
    ### end Alembic commands ###
