"""empty message

Revision ID: f0b1830d528
Revises: bf599e87f79
Create Date: 2014-07-12 11:52:28.856236

"""

# revision identifiers, used by Alembic.
revision = 'f0b1830d528'
down_revision = 'bf599e87f79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system', sa.String(length=12), nullable=True),
    sa.Column('planet', sa.String(length=6), nullable=True),
    sa.Column('moon', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    ### end Alembic commands ###
